version: '3.7'

services:

  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/:/srv/groupq/server
    command: echo 'ready server' && npm run dev

  client:
    build: ./client
    expose:
      - ${REACT_APP_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/:/srv/groupq/client
      - ./client/public:/srv/client/public
    links:
      - server
    command: echo 'ready client' && npm run start