version: "3"
services:
    groupq-server:
        build: ./server
        depends_on:
            - postgres
        command: sh scripts/start.sh
        ports:
            - "3000:3000"
            - "9229:9229"
        
    postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_DB: groupq
            POSTGRES_USER: gqadmin
        ports:
            - "5432:5432"